### ISSUE TITLE
不在项目根目录运营脚本时出错

### ISSUE THREAD

**Issue by shanderlam** [upyun-dev/loadconfig#2]
如在 bin 目录下运行脚本 xxx ，将报以下错误

```
$ ./xxx
module.js:487
    throw err;
    ^

Error: Cannot find module '/path/to/project/bin/package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at loadConfig (/path/to/project/node_modules/loadconfig/index.js:26:31)
    at Object.<anonymous> (/path/to/project/bootstrap.js:17:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

**Comment by shanderlam** [comment]
在这种情况下可以不理会环境变量中的配置，打印一个警告信息，告诉调用者无法从环境变量中加载配置
